# Generated by Django 4.2.25 on 2026-01-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('both', 'Both'), ('other', 'Other')], default='other', max_length=20)),
                ('purpose', models.CharField(max_length=100)),
                ('management_preference', models.CharField(blank=True, choices=[('retained_management', 'Retained Management'), ('run_myself', 'Run Myself')], max_length=30, null=True)),
                ('company_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('shareholders_working_in_business', models.BooleanField(blank=True, default=False, null=True)),
                ('taking_salary', models.BooleanField(blank=True, default=False, null=True)),
                ('salary_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('property_own_or_rent', models.CharField(blank=True, choices=[('own', 'own'), ('rent', 'rent')], max_length=10, null=True)),
                ('property_market_rent_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('adjust_industry_multipliers', models.BooleanField(blank=True, default=False, null=True)),
                ('lower_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upper_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spoken_to_accountant', models.BooleanField(blank=True, default=False, null=True)),
                ('spoken_to_broker', models.BooleanField(blank=True, default=False, null=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('predicted_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('predicted_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('non_recurring_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_payable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('interest_receivable', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('amortisation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('net_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_number', models.CharField(blank=True, max_length=50, null=True)),
                ('valuation_low', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valuation_high', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sde', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
