# Generated by Django 4.2.25 on 2025-11-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_sector', models.CharField(max_length=100)),
                ('shareholders_working_in_business', models.BooleanField(default=False)),
                ('taking_full_market_salary', models.BooleanField(default=False)),
                ('salary_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('property_own_or_rent', models.CharField(choices=[('Own', 'Own'), ('Rent', 'Rent')], max_length=10)),
                ('property_market_rent_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('adjust_industry_multipliers', models.BooleanField(default=False)),
                ('lower_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('upper_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purpose', models.CharField(max_length=100)),
                ('spoken_to_accountant', models.BooleanField(default=False)),
                ('spoken_to_broker', models.BooleanField(default=False)),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=15)),
                ('predicted_turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('predicted_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('non_recurring_expenses', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_payable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('interest_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amortisation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_assets', models.DecimalField(decimal_places=2, max_digits=15)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('company_number', models.CharField(blank=True, max_length=50)),
                ('valuation_low', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('valuation_high', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('sde', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
