# Generated by Django 4.2.25 on 2025-11-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='property_market_rent_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='salary_adjustment',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='taking_salary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
