# Generated by Django 4.2.25 on 2026-01-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lead_property_market_rent_adjustment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='buyer_estimated_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='management_preference',
            field=models.CharField(blank=True, choices=[('retained_management', 'Retained Management'), ('run_myself', 'Run Myself')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('both', 'Both'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='shareholders_working_in_business',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
