# Generated by Django 4.2.25 on 2026-01-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lead_buyer_estimated_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='buyer_estimated_salary',
        ),
    ]
