# Generated by Django 4.2.25 on 2026-01-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_buyer_estimated_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
